### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by diimpp** [gulafaran/flashgrab#1]
Hi,

Thank you for a implementation of missed tool.

I'm experiencing ld error in some obscure cases, but this is looks like fixing it.

```
TARGET_LINK_LIBRARIES(flashgrab X11)
```

Could you please add project licence and git tag for a version?
It would be helpful for packaging your tool.

Here you can see initial ebuild for gentoo http://pastebin.com/aL3V3ahg (I'm not the author)

Regards.

**Comment by gulafaran** [comment]
added beerware license, and TARGET_LINK_LIBRARIES(flashgrab X11) , for you. happy emerging. :)
